// Gender restrictions
const onlyF = ["nidoran-f", "nidorina", "nidoqueen", "illumise", "latias", "froslass", "wormadam", "wormadam-sandy", "wormadam-trash", "vespiquen", "salazzle", "happiny", "chansey", "blissey", "kangaskhan", "smoochum", "jynx", "miltank", "cresselia", "petilil", "lilligant", "lilligant-hisui", "vullaby", "mandibuzz", "flabebe", "flabebe-yellow", "flabebe-orange", "flabebe-blue", "flabebe-white", "floette", "floette-yellow", "floette-orange", "floette-blue", "floette-white", "florges", "florges-yellow", "florges-orange", "florges-blue", "florges-white", "bounsweet", "steenee", "tsareena", "hatenna", "hattrem", "hatterene", "milcery", "alcremie", "enamorus", "enamorus-therian"];

const onlyM = ["pikachu-original-cap", "pikachu-hoenn-cap", "pikachu-sinnoh-cap", "pikachu-unova-cap", "pikachu-kalos-cap", "pikachu-alola-cap", "pikachu-partner-cap", "pikachu-world-cap", "nidoran-m", "nidorino", "nidoking", "volbeat", "latios", "gallade", "mothim", "tyrogue", "hitmonlee", "hitmonchan", "hitmontop", "tauros", "throh", "sawk", "rufflet", "braviary", "braviary-hisui", "tornadus", "tornadus-therian", "thundurus", "thundurus-therian", "landorus", "landorus-therian", "greninja-ash", "impidimp", "morgrem", "grimmsnarl"];

const onlyU = ["magnemite", "magneton", "voltorb", "voltorb-hisui", "electrode", "electrode-hisui", "staryu", "starmie", "porygon", "porygon2", "shedinja", "lunatone", "solrock", "baltoy", "claydol", "beldum", "metang", "metagross", "bronzor", "bronzong", "magnezone", "porygon-z", "rotom", "rotom-heat", "rotom-wash", "rotom-frost", "rotom-fan", "rotom-mow", "phione", "manaphy", "klink", "klang", "klinklang", "cryogonal", "golett", "golurk", "carbink", "minior", "minior-orange", "minior-yellow", "minior-green", "minior-blue", "minior-indigo", "minior-violet", "dhelmise", "sinistea", "polteageist", "falinks", "ditto", "articuno", "articuno-galar", "zapdos", "zapdos-galar", "moltres", "moltres-galar", "mewtwo", "mew", "unown", "unown-b", "unown-c", "unown-d", "unown-e", "unown-f", "unown-g", "unown-h", "unown-i", "unown-j", "unown-k", "unown-l", "unown-m", "unown-n", "unown-o", "unown-p", "unown-q", "unown-r", "unown-s", "unown-t", "unown-u", "unown-v", "unown-w", "unown-x", "unown-y", "unown-z", "unown-question", "unown-exclamation", "raikou", "entei", "suicune", "lugia", "ho-oh", "celebi", "regirock", "regice", "registeel", "kyogre", "groudon", "rayquaza", "jirachi", "deoxys", "deoxys-attack", "deoxys-defense", "deoxys-speed", "uxie", "mesprit", "azelf", "dialga", "palkia", "regigigas", "giratina", "darkrai", "shaymin", "shaymin-sky", "arceus", "victini", "cobalion", "terrakion", "virizion", "reshiram", "zekrom", "kyurem", "keldeo", "keldeo-resolute", "meloetta", "genesect", "xerneas", "yveltal", "zygarde", "diancie", "hoopa", "volcanion", "type-null", "silvally", "tapu-koko", "tapu-lele", "tapu-bulu", "tapu-fini", "cosmog", "cosmoem", "solgaleo", "lunala", "nihilego", "buzzwole", "pheromosa", "xurkitree", "celesteela", "kartana", "guzzlord", "necrozma", "magearna", "marshadow", "poipole", "naganadel", "stakataka", "blacephalon", "zeraora", "meltan", "melmetal", "dracozolt", "arctozolt", "dracovish", "arctovish", "zacian", "zamazenta", "eternatus", "zarude", "zarude-dada", "regieleki", "regidrago", "glastrier", "spectrier", "calyrex"];

// Gender-specific sprites
const spriteF = ["basculegion", "frillish", "hippopotas", "hippowdon", "indeedee", "jellicent", "meowstic", "pikachu", "pyroar", "unfezant", "wobbuffet"];

// Origin Marks
const games = {
	"go":		{"name": "GO",					"mark": "go"},
	"scar":		{"name": "Scarlet",				"mark": "paldea"},
	"vio":		{"name": "Violet",				"mark": "paldea"},
	"sw":		{"name": "Sword",				"mark": "galar"},
	"sh":		{"name": "Shield",				"mark": "galar"},
	"bd":		{"name": "Brilliant Diamond",	"mark": "bdsp"},
	"sp":		{"name": "Shining Pearl",		"mark": "bdsp"},
	"pla":		{"name": "Legends: Arceus",		"mark": "hisui"},
	"sun":		{"name": "Sun",					"mark": "clover"},
	"moon":		{"name": "Moon",				"mark": "clover"},
	"usun":		{"name": "Ultra Sun",			"mark": "clover"},
	"umoon":	{"name": "Ultra Moon",			"mark": "clover"},
	"lgp":		{"name": "Let's Go, Pikachu!",	"mark": "lets-go"},
	"lge":		{"name": "Let's Go, Eevee!",	"mark": "lets-go"},
	"x":		{"name": "X",					"mark": "pentagon"},
	"y":		{"name": "Y",					"mark": "pentagon"},
	"or":		{"name": "Omega Ruby",			"mark": "pentagon"},
	"as":		{"name": "Alpha Sapphire",		"mark": "pentagon"},
	"black":	{"name": "Black",				"mark": null},
	"white":	{"name": "White",				"mark": null},
	"black2":	{"name": "Black 2",				"mark": null},
	"white2":	{"name": "White 2",				"mark": null},
	"diamond":	{"name": "Diamond",				"mark": null},
	"pearl":	{"name": "Pearl",				"mark": null},
	"platinum":	{"name": "Platinum",			"mark": null},
	"hg":		{"name": "HeartGold",			"mark": null},
	"ss":		{"name": "SoulSilver",			"mark": null},
	"ruby":		{"name": "Ruby",				"mark": null},
	"sapphire":	{"name": "Sapphire",			"mark": null},
	"emerald":	{"name": "Emerald",				"mark": null},
	"fr":		{"name": "FireRed",				"mark": null},
	"lg":		{"name": "LeafGreen",			"mark": null},
	"colosseum":{"name": "Colosseum",			"mark": null},
	"xd":		{"name": "XD: Gale of Darkness","mark": null},
	"gold":		{"name": "Gold",				"mark": "game-boy"},
	"silver":	{"name": "Silver",				"mark": "game-boy"},
	"crystal":	{"name": "Crystal",				"mark": "game-boy"},
	"red-jpn":	{"name": "Red (JPN)",			"mark": "game-boy"},
	"green":	{"name": "Green",				"mark": "game-boy"},
	"blue-jpn":	{"name": "Blue (JPN)",			"mark": "game-boy"},
	"red-eng":	{"name": "Red (ENG)",			"mark": "game-boy"},
	"blue-eng":	{"name": "Blue (ENG)",			"mark": "game-boy"},
	"yellow":	{"name": "Yellow",				"mark": "game-boy"}
};

// Mint sprites
const mints = {
	"Lonely":	"atk",
	"Adamant":	"atk",
	"Naughty":	"atk",
	"Brave":	"atk",
	"Bold":		"def",
	"Impish":	"def",
	"Lax":		"def",
	"Relaxed":	"def",
	"Modest":	"spa",
	"Mild": 	"spa",
	"Rash":		"spa",
	"Quiet":	"spa",
	"Calm":		"spd",
	"Gentle":	"spd",
	"Careful":	"spd",
	"Sassy":	"spd",
	"Timid":	"spe",
	"Hasty":	"spe",
	"Jolly":	"spe",
	"Naive":	"spe",
	"Serious":	"neutral"
}

// Ribbons
const ribbonIDs = {"Event": "e", "Marks": "m", "Gen III": 3, "Gen IV": 4, "Gen VI": 6, "Gen VII": 7, "Gen VIII": 8};
const allRibbons = {
	"champion-ribbon":				{"name": "Champion Ribbon",				"gen": 3,	"title": "the Champion",			"available": ["ruby", "sapphire", "emerald", "fr", "lg"], "desc": "A Ribbon awarded for clearing the Pokémon League and entering the Hall of Fame somewhere long ago."},
	"sinnoh-champion-ribbon":		{"name": "Sinnoh Champion Ribbon",		"gen": 4,	"title": "the Sinnoh Champion",		"available": ["diamond", "pearl", "platinum", "bd", "sp"], "desc": "A Ribbon awarded for beating the Sinnoh Champion and entering the Sinnoh Hall of Fame."},
	"kalos-champion-ribbon":		{"name": "Kalos Champion Ribbon",		"gen": 6,	"title": "the Kalos Champion",		"available": ["x", "y"], "desc": "A Ribbon awarded for beating the Kalos Champion and entering the Kalos Hall of Fame."},
	"hoenn-champion-ribbon":		{"name": "Hoenn Champion Ribbon",		"gen": 6,	"title": "the Hoenn Champion",		"available": ["or", "as"], "desc": "A Ribbon awarded for beating the Hoenn Champion and entering the Hoenn Hall of Fame."},
	"alola-champion-ribbon":		{"name": "Alola Champion Ribbon",		"gen": 7,	"title": "the Alola Champion",		"available": ["sun", "moon", "usun", "umoon"], "desc": "A Ribbon awarded for becoming the Alola Champion and entering the Alola Hall of Fame."},
	"galar-champion-ribbon":		{"name": "Galar Champion Ribbon",		"gen": 8,	"title": "the Galar Champion",		"available": ["sw", "sh"], "desc": "A Ribbon awarded for becoming the Galar Champion and entering the Galar Hall of Fame."},
	"cool-ribbon-hoenn":			{"name": "Cool Ribbon",					"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Cool Contest Normal Rank winner!"},
	"cool-ribbon-super-hoenn":		{"name": "Cool Ribbon Super",			"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Cool Contest Super Rank winner!"},
	"cool-ribbon-hyper-hoenn":		{"name": "Cool Ribbon Hyper",			"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Cool Contest Hyper Rank winner!"},
	"cool-ribbon-master-hoenn":		{"name": "Cool Ribbon Master",			"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Cool Contest Master Rank winner!"},
	"beauty-ribbon-hoenn":			{"name": "Beauty Ribbon",				"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Beauty Contest Normal Rank winner!"},
	"beauty-ribbon-super-hoenn":	{"name": "Beauty Ribbon Super",			"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Beauty Contest Super Rank winner!"},
	"beauty-ribbon-hyper-hoenn":	{"name": "Beauty Ribbon Hyper",			"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Beauty Contest Hyper Rank winner!"},
	"beauty-ribbon-master-hoenn":	{"name": "Beauty Ribbon Master",		"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Beauty Contest Master Rank winner!"},
	"cute-ribbon-hoenn":			{"name": "Cute Ribbon",					"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Cute Contest Normal Rank winner!"},
	"cute-ribbon-super-hoenn":		{"name": "Cute Ribbon Super",			"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Cute Contest Super Rank winner!"},
	"cute-ribbon-hyper-hoenn":		{"name": "Cute Ribbon Hyper",			"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Cute Contest Hyper Rank winner!"},
	"cute-ribbon-master-hoenn":		{"name": "Cute Ribbon Master",			"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Cute Contest Master Rank winner!"},
	"smart-ribbon-hoenn":			{"name": "Smart Ribbon",				"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Smart Contest Normal Rank winner!"},
	"smart-ribbon-super-hoenn":		{"name": "Smart Ribbon Super",			"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Smart Contest Super Rank winner!"},
	"smart-ribbon-hyper-hoenn":		{"name": "Smart Ribbon Hyper",			"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Smart Contest Hyper Rank winner!"},
	"smart-ribbon-master-hoenn":	{"name": "Smart Ribbon Master",			"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Smart Contest Master Rank winner!"},
	"tough-ribbon-hoenn":			{"name": "Tough Ribbon",				"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Tough Contest Normal Rank winner!"},
	"tough-ribbon-super-hoenn":		{"name": "Tough Ribbon Super",			"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Tough Contest Super Rank winner!"},
	"tough-ribbon-hyper-hoenn":		{"name": "Tough Ribbon Hyper",			"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Tough Contest Hyper Rank winner!"},
	"tough-ribbon-master-hoenn":	{"name": "Tough Ribbon Master",			"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Hoenn Tough Contest Master Rank winner!"},
	"cool-ribbon-sinnoh":			{"name": "Cool Ribbon",					"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Cool Category Normal Rank winner!"},
	"cool-ribbon-great-sinnoh":		{"name": "Cool Ribbon Great",			"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Cool Category Great Rank winner!"},
	"cool-ribbon-ultra-sinnoh":		{"name": "Cool Ribbon Ultra",			"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Cool Category Ultra Rank winner!"},
	"cool-ribbon-master-sinnoh":	{"name": "Cool Ribbon Master",			"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Cool Category Master Rank winner!"},
	"beauty-ribbon-sinnoh":			{"name": "Beauty Ribbon",				"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Beauty Category Normal Rank winner!"},
	"beauty-ribbon-great-sinnoh":	{"name": "Beauty Ribbon Great",			"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Beauty Category Great Rank winner!"},
	"beauty-ribbon-ultra-sinnoh":	{"name": "Beauty Ribbon Ultra",			"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Beauty Category Ultra Rank winner!"},
	"beauty-ribbon-master-sinnoh":	{"name": "Beauty Ribbon Master",		"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Beauty Category Master Rank winner!"},
	"cute-ribbon-sinnoh":			{"name": "Cute Ribbon",					"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Cute Category Normal Rank winner!"},
	"cute-ribbon-great-sinnoh":		{"name": "Cute Ribbon Great",			"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Cute Category Great Rank winner!"},
	"cute-ribbon-ultra-sinnoh":		{"name": "Cute Ribbon Ultra",			"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Cute Category Ultra Rank winner!"},
	"cute-ribbon-master-sinnoh":	{"name": "Cute Ribbon Master",			"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Cute Category Master Rank winner!"},
	"smart-ribbon-sinnoh":			{"name": "Smart Ribbon",				"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Smart Category Normal Rank winner!"},
	"smart-ribbon-great-sinnoh":	{"name": "Smart Ribbon Great",			"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Smart Category Great Rank winner!"},
	"smart-ribbon-ultra-sinnoh":	{"name": "Smart Ribbon Ultra",			"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Smart Category Ultra Rank winner!"},
	"smart-ribbon-master-sinnoh":	{"name": "Smart Ribbon Master",			"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Smart Category Master Rank winner!"},
	"tough-ribbon-sinnoh":			{"name": "Tough Ribbon",				"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Tough Category Normal Rank winner!"},
	"tough-ribbon-great-sinnoh":	{"name": "Tough Ribbon Great",			"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Tough Category Great Rank winner!"},
	"tough-ribbon-ultra-sinnoh":	{"name": "Tough Ribbon Ultra",			"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Tough Category Ultra Rank winner!"},
	"tough-ribbon-master-sinnoh":	{"name": "Tough Ribbon Master",			"gen": 4,										"available": ["diamond", "pearl", "platinum"], "desc": "Super Contest Tough Category Master Rank winner!"},
	"coolness-master-ribbon":		{"name": "Coolness Master Ribbon",		"gen": 6,	"title": "the Former Star",			"available": ["or", "as", "bd", "sp"], "desc": "A Ribbon awarded to a Pokémon that has perfectly embodied Coolness in Pokémon Contests."},
	"beauty-master-ribbon":			{"name": "Beauty Master Ribbon",		"gen": 6,	"title": "the Vintage Beauty",		"available": ["or", "as", "bd", "sp"], "desc": "A Ribbon awarded to a Pokémon that has perfectly embodied Beauty in Pokémon Contests."},
	"cuteness-master-ribbon":		{"name": "Cuteness Master Ribbon",		"gen": 6,	"title": "the Former Idol",			"available": ["or", "as", "bd", "sp"], "desc": "A Ribbon awarded to a Pokémon that has perfectly embodied Cuteness in Pokémon Contests."},
	"cleverness-master-ribbon":		{"name": "Cleverness Master Ribbon",	"gen": 6,	"title": "the Historic Genius",		"available": ["or", "as", "bd", "sp"], "desc": "A Ribbon awarded to a Pokémon that has perfectly embodied Cleverness in Pokémon Contests."},
	"toughness-master-ribbon":		{"name": "Toughness Master Ribbon",		"gen": 6,	"title": "the Formerly Buff",		"available": ["or", "as", "bd", "sp"], "desc": "A Ribbon awarded to a Pokémon that has perfectly embodied Toughness in Pokémon Contests."},
	"contest-star-ribbon":			{"name": "Contest Star Ribbon",			"gen": 6,	"title": "the Shining Star",		"available": ["or", "as", "bd", "sp"], "desc": "A Ribbon awarded to a Pokémon that has performed superbly in every kind of contest."},
	"twinkling-star-ribbon":		{"name": "Twinkling Star Ribbon",		"gen": 8,										"available": ["bd", "sp"], "desc": "A Ribbon awarded to a Pokémon that has perfectly embodied shining brilliance in Super Contest Shows."},
	"contest-memory-ribbon":		{"name": "Contest Memory Ribbon",		"gen": 6,	"title": "the Treasured Memory",	"available": ["x", "y", "or", "as"], "desc": "A commemorative Ribbon representing all of the Ribbons you collected for contests somewhere long ago."},
	"contest-memory-ribbon-gold":	{"name":"Contest Memory Ribbon",		"gen": 6,	"title": "the Treasured Memory",	"available": ["x", "y", "or", "as"], "desc": "A commemorative Ribbon representing all of the Ribbons you collected for contests somewhere long ago."},
	"winning-ribbon":				{"name": "Winning Ribbon",				"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Ribbon awarded for clearing Hoenn's Battle Tower's Lv. 50 challenge."},
	"victory-ribbon":				{"name": "Victory Ribbon",				"gen": 3,										"available": ["ruby", "sapphire", "emerald"], "desc": "Ribbon awarded for clearing Hoenn's Battle Tower's Lv. 100 challenge."},
	"ability-ribbon":				{"name": "Ability Ribbon",				"gen": 4,										"available": ["diamond", "pearl", "platinum", "hg", "ss"], "desc": "A Ribbon awarded for defeating the Tower Tycoon at the Battle Tower."},
	"great-ability-ribbon":			{"name": "Great Ability Ribbon",		"gen": 4,										"available": ["diamond", "pearl", "platinum", "hg", "ss"], "desc": "A Ribbon awarded for defeating the Tower Tycoon at the Battle Tower."},
	"double-ability-ribbon":		{"name": "Double Ability Ribbon",		"gen": 4,										"available": ["diamond", "pearl", "platinum", "hg", "ss"], "desc": "A Ribbon awarded for completing the Battle Tower Double challenge."},
	"multi-ability-ribbon": 		{"name": "Multi Ability Ribbon",		"gen": 4,										"available": ["diamond", "pearl", "platinum", "hg", "ss"], "desc": "A Ribbon awarded for completing the Battle Tower Multi challenge."},
	"pair-ability-ribbon":			{"name": "Pair Ability Ribbon",			"gen": 4,										"available": ["diamond", "pearl", "platinum", "hg", "ss"], "desc": "A Ribbon awarded for completing the Battle Tower Link Multi challenge."},
	"world-ability-ribbon":			{"name": "World Ability Ribbon",		"gen": 4,										"available": ["diamond", "pearl", "platinum", "hg", "ss"], "desc": "A Ribbon awarded for completing the Wi-Fi Battle Tower challenge."},
	"battle-memory-ribbon":			{"name": "Battle Memory Ribbon",		"gen": 6,	"title": "the Exciting Memory",		"available": ["x", "y", "or", "as"], "desc": "A commemorative Ribbon representing all of the Ribbons you collected for battling somewhere long ago."},
	"battle-memory-ribbon-gold":	{"name": "Battle Memory Ribbon",		"gen": 6,	"title": "the Exciting Memory",		"available": ["x", "y", "or", "as"], "desc": "A commemorative Ribbon representing all of the Ribbons you collected for battling somewhere long ago."},
	"skillful-battler-ribbon":		{"name": "Skillful Battler Ribbon",		"gen": 6,	"title": "the Veteran",				"available": ["x", "y", "or", "as"], "desc": "A Ribbon that can be given to a Pokémon that has achieved victory in difficult battles."},
	"expert-battler-ribbon":		{"name": "Expert Battler Ribbon",		"gen": 6,	"title": "the Master",				"available": ["x", "y", "or", "as"], "desc": "A Ribbon that can be given to a brave Pokémon that has honed its battle skills to an art."},
	"battle-tree-great-ribbon":		{"name": "Battle Tree Great Ribbon",	"gen": 7,	"title": "the Tree Victor",			"available": ["sun", "moon", "usun", "umoon"], "desc": "A Ribbon awarded for winning against a Battle Legend in the Battle Tree."},
	"battle-tree-master-ribbon":	{"name": "Battle Tree Master Ribbon",	"gen": 7,	"title": "the Tree Master", 		"available": ["sun", "moon", "usun", "umoon"], "desc": "A Ribbon awarded for winning against a Battle Legend in super battles in the Battle Tree."},
	"tower-master-ribbon":			{"name": "Tower Master Ribbon",			"gen": 8,	"title": "the Tower Master",		"available": ["sw", "sh", "bd", "sp"], "desc": "A Ribbon awarded for winning against a champion in the Battle Tower."},
	"artist-ribbon":				{"name": "Artist Ribbon",				"gen": 3,	"title": "the Model for Paintings",	"available": ["ruby", "sapphire", "emerald"], "desc": "A Ribbon awarded for being chosen as a super sketch model in the Hoenn region."},
	"effort-ribbon":				{"name": "Effort Ribbon",				"gen": 3,	"title": "the Once Well-Trained",	"available": ["ruby", "sapphire", "emerald", "diamond", "pearl", "platinum", "hg", "ss", "x", "y", "or", "as", "sun", "moon", "usun", "umoon", "sw", "sh", "bd", "sp"], "desc": "A Ribbon awarded for being an exceptionally hard worker."},
	"alert-ribbon":					{"name": "Alert Ribbon",				"gen": 4,	"title": "the Once Vigilant",		"available": ["diamond", "pearl", "platinum", "hg", "ss", "x", "y", "or", "as", "bd", "sp"], "desc": "A Ribbon for recalling an invigorating event that created life energy."},
	"shock-ribbon":					{"name": "Shock Ribbon",				"gen": 4,	"title": "the Once Cowardly",		"available": ["diamond", "pearl", "platinum", "hg", "ss", "x", "y", "or", "as", "bd", "sp"], "desc": "A Ribbon for recalling a thrilling event that made life more exciting."},
	"downcast-ribbon":				{"name": "Downcast Ribbon",				"gen": 4,	"title": "the Once Shaken",			"available": ["diamond", "pearl", "platinum", "hg", "ss", "x", "y", "or", "as", "bd", "sp"], "desc": "A Ribbon for recalling feelings of sadness that added spice to life."},
	"careless-ribbon":				{"name": "Careless Ribbon",				"gen": 4,	"title": "the Once Imperfect",		"available": ["diamond", "pearl", "platinum", "hg", "ss", "x", "y", "or", "as", "bd", "sp"], "desc": "A Ribbon for recalling a careless error that helped steer life decisions."},
	"relax-ribbon":					{"name": "Relax Ribbon",				"gen": 4,	"title": "the Once Well-Rested",	"available": ["diamond", "pearl", "platinum", "hg", "ss", "x", "y", "or", "as", "bd", "sp"], "desc": "A Ribbon for recalling a refreshing event that added sparkle to life."},
	"snooze-ribbon":				{"name": "Snooze Ribbon",				"gen": 4,	"title": "the Once Sleepy",			"available": ["diamond", "pearl", "platinum", "hg", "ss", "x", "y", "or", "as", "bd", "sp"], "desc": "A Ribbon for recalling a deep slumber that made life soothing."},
	"smile-ribbon":					{"name": "Smile Ribbon",				"gen": 4,	"title": "the Once Cheery",			"available": ["diamond", "pearl", "platinum", "hg", "ss", "x", "y", "or", "as", "bd", "sp"], "desc": "A Ribbon for recalling that smiles enrich the quality of life."},
	"gorgeous-ribbon":				{"name": "Gorgeous Ribbon",				"gen": 4,	"title": "the Gorgeous",			"available": ["diamond", "pearl", "platinum", "or", "as", "bd", "sp"], "desc": "An extraordinarily gorgeous and extravagant Ribbon."},
	"royal-ribbon":					{"name": "Royal Ribbon",				"gen": 4,	"title": "the Royal",				"available": ["diamond", "pearl", "platinum", "or", "as", "bd", "sp"], "desc": "An incredibly regal Ribbon with an air of nobility."},
	"gorgeous-royal-ribbon":		{"name": "Gorgeous Royal Ribbon",		"gen": 4,	"title": "the Gorgeous Royal",		"available": ["diamond", "pearl", "platinum", "or", "as", "bd", "sp"], "desc": "A gorgeous and regal Ribbon that is the peak of fabulous."},
	"footprint-ribbon":				{"name": "Footprint Ribbon",			"gen": 4,	"title": "the Strutter",			"available": ["diamond", "pearl", "platinum", "x", "y", "or", "as", "sun", "moon", "usun", "umoon", "bd", "sp"], "desc": "A Ribbon awarded to a Pokémon deemed to have a top-quality footprint."},
	"legend-ribbon":				{"name": "Legend Ribbon",				"gen": 4,	"title": "the Living Legend",		"available": ["hg", "ss"], "desc": "A Ribbon awarded for setting a legendary record."},
	"best-friends-ribbon":			{"name": "Best Friends Ribbon",			"gen": 6,	"title": "the Great Friend",		"available": ["x", "y", "or", "as", "sun", "moon", "usun", "umoon", "sw", "sh", "bd", "sp"], "desc": "A Ribbon that can be given to a Pokémon with which you share a close and meaningful bond."},
	"training-ribbon":				{"name": "Training Ribbon",				"gen": 6,	"title": "the Tried and True",		"available": ["x", "y", "or", "as"], "desc": "A Ribbon that can be given to a Pokémon that has overcome rigorous trials and training."},
	"battle-royal-master-ribbon":	{"name": "Battle Royal Master Ribbon",	"gen": 7,	"title": "the Royal Master",		"available": ["sun", "moon", "usun", "umoon"], "desc": "A Ribbon that can be given to a Pokémon that has achieved victory in the Battle Royal."},
	"master-rank-ribbon":			{"name": "Master Rank Ribbon",			"gen": 8,	"title": "the Rank Master",			"available": ["sw", "sh"], "desc": "A Ribbon awarded for winning against a Trainer in the Master Ball Tier of Ranked Battles."},
	"hisui-ribbon":					{"name": "Hisui Ribbon",				"gen": 8,										"available": ["pla"], "desc": "A Ribbon awarded to a Pokémon that posed for a photograph in Hisui in the distant past."},
	"country-ribbon":				{"name": "Country Ribbon",				"gen": 3,	"title": "the Victor",				"available": null, "desc": "A Ribbon awarded to a Pokémon League Champion."},
	"national-ribbon":				{"name": "National Ribbon",				"gen": 3,	"title": "the Triumphant",			"available": ["colosseum", "xd"], "desc": "A Ribbon awarded for overcoming all difficult challenges."},
	"earth-ribbon":					{"name": "Earth Ribbon",				"gen": 3,	"title": "the 100× Victorious",		"available": ["colosseum", "xd"], "desc": "A Ribbon awarded for winning one hundred battles in a row."},
	"world-ribbon":					{"name": "World Ribbon",				"gen": 3,	"title": "the World Conqueror",		"available": null, "desc": "A Ribbon awarded to a Pokémon League Champion."},
	"classic-ribbon":				{"name": "Classic Ribbon",				"gen": 4,	"title": "the Pokémon Fan",			"available": null, "desc": "A Ribbon that proclaims love for Pokémon."},
	"premier-ribbon":				{"name": "Premier Ribbon",				"gen": 4,	"title": "the Celebratory",			"available": null, "desc": "A Ribbon awarded for a special holiday."},
	"event-ribbon":					{"name": "Event Ribbon",				"gen": 5,	"title": "the Festive",				"available": null, "desc": "A Ribbon awarded for participating in a special Pokémon event."},
	"birthday-ribbon":				{"name": "Birthday Ribbon",				"gen": 5,	"title": "the Best Buddy",			"available": null, "desc": "A Ribbon that commemorates a birthday."},
	"special-ribbon":				{"name": "Special Ribbon",				"gen": 5,	"title": "the Premium",				"available": null, "desc": "A special Ribbon for a special day."},
	"souvenir-ribbon":				{"name": "Souvenir Ribbon",				"gen": 5,	"title": "the Cherished",			"available": null, "desc": "A Ribbon for cherishing a special memory."},
	"wishing-ribbon":				{"name": "Wishing Ribbon",				"gen": 5,	"title": "the Wish Granter",		"available": null, "desc": "A Ribbon said to make your wish come true."},
	"battle-champion-ribbon":		{"name": "Battle Champion Ribbon",		"gen": 5,	"title": "the Battle Champion",		"available": null, "desc": "A Ribbon awarded to a Battle Competition Champion."},
	"world-champion-ribbon":		{"name": "World Champion Ribbon",		"gen": 5,	"title": "the World Champion",		"available": null, "desc": "A Ribbon awarded to a World Champion in the Pokémon World Championships."},

	"lunchtime-mark":				{"name": "Lunchtime Mark",				"gen": 8,	"title": "the Peckish",				"available": null, "mark": true, "desc": "A mark for a peckish Pokémon."},
	"sleepy-time-mark":				{"name": "Sleepy-Time Mark",			"gen": 8,	"title": "the Sleepy",				"available": null, "mark": true, "desc": "A mark for a sleepy Pokémon."},
	"dusk-mark":					{"name": "Dusk Mark",					"gen": 8,	"title": "the Dozy",				"available": null, "mark": true, "desc": "A mark for a dozy Pokémon."},
	"dawn-mark":					{"name": "Dawn Mark",					"gen": 8,	"title": "the Early Riser",			"available": null, "mark": true, "desc": "A mark for an early-riser Pokémon."},
	"cloudy-mark":					{"name": "Cloudy Mark",					"gen": 8,	"title": "the Cloud Watcher",		"available": null, "mark": true, "desc": "A mark for a cloud-watching Pokémon."},
	"rainy-mark":					{"name": "Rainy Mark",					"gen": 8,	"title": "the Sodden",				"available": null, "mark": true, "desc": "A mark for a sodden Pokémon."},
	"stormy-mark":					{"name": "Stormy Mark",					"gen": 8,	"title": "the Thunderstruck",		"available": null, "mark": true, "desc": "A mark for a thunderstruck Pokémon."},
	"snowy-mark":					{"name": "Snowy Mark",					"gen": 8,	"title": "the Snow Frolicker",		"available": null, "mark": true, "desc": "A mark for a snow-frolicking Pokémon."},
	"blizzard-mark":				{"name": "Blizzard Mark",				"gen": 8,	"title": "the Shivering",			"available": null, "mark": true, "desc": "A mark for a shivering Pokémon."},
	"dry-mark":						{"name": "Dry Mark",					"gen": 8,	"title": "the Parched",				"available": null, "mark": true, "desc": "A mark for a parched Pokémon."},
	"sandstorm-mark":				{"name": "Sandstone Mark",				"gen": 8,	"title": "the Sandswept",			"available": null, "mark": true, "desc": "A mark for a sandswept Pokémon."},
	"misty-mark":					{"name": "Misty Mark",					"gen": 8,	"title": "the Mist Drifter",		"available": null, "mark": true, "desc": "A mark for a mist-drifter Pokémon."},
	"fishing-mark":					{"name": "Fishing Mark",				"gen": 8,	"title": "the Catch of the Day",	"available": null, "mark": true, "desc": "A mark for a catch-of-the-day Pokémon."},
	"curry-mark":					{"name": "Curry Mark",					"gen": 8,	"title": "the Curry Connoisseur",	"available": null, "mark": true, "desc": "A mark for a curry-connoisseur Pokémon."},
	"uncommon-mark":				{"name": "Uncommon Mark",				"gen": 8,	"title": "the Sociable",			"available": null, "mark": true, "desc": "A mark for a sociable Pokémon."},
	"rare-mark":					{"name": "Rare Mark",					"gen": 8,	"title": "the Recluse",				"available": null, "mark": true, "desc": "A mark for a reclusive Pokémon."},
	"rowdy-mark":					{"name": "Rowdy Mark",					"gen": 8,	"title": "the Rowdy",				"available": null, "mark": true, "desc": "A mark for a rowdy Pokémon."},
	"absent-minded-mark":			{"name": "Absent-Minded Mark",			"gen": 8,	"title": "the Spacey",				"available": null, "mark": true, "desc": "A mark for a spacey Pokémon."},
	"jittery-mark":					{"name": "Jittery Mark",				"gen": 8,	"title": "the Anxious",				"available": null, "mark": true, "desc": "A mark for an anxious Pokémon."},
	"excited-mark":					{"name": "Excited Mark",				"gen": 8,	"title": "the Giddy",				"available": null, "mark": true, "desc": "A mark for a giddy Pokémon."},
	"charismatic-mark":				{"name": "Charismatic Mark",			"gen": 8,	"title": "the Radiant",				"available": null, "mark": true, "desc": "A mark for a radiant Pokémon."},
	"calmness-mark":				{"name": "Calmness Mark",				"gen": 8,	"title": "the Serene",				"available": null, "mark": true, "desc": "A mark for a serene Pokémon."},
	"intense-mark":					{"name": "Intense Mark",				"gen": 8,	"title": "the Feisty",				"available": null, "mark": true, "desc": "A mark for a feisty Pokémon."},
	"zoned-out-mark":				{"name": "Zoned-Out Mark",				"gen": 8,	"title": "the Daydreamer",			"available": null, "mark": true, "desc": "A mark for a daydreaming Pokémon."},
	"joyful-mark":					{"name": "Joyful Mark",					"gen": 8,	"title": "the Joyful",				"available": null, "mark": true, "desc": "A mark for a joyful Pokémon."},
	"angry-mark":					{"name": "Angry Mark",					"gen": 8,	"title": "the Furious",				"available": null, "mark": true, "desc": "A mark for a furious Pokémon."},
	"smiley-mark":					{"name": "Smiley Mark",					"gen": 8,	"title": "the Beaming",				"available": null, "mark": true, "desc": "A mark for a beaming Pokémon."},
	"teary-mark":					{"name": "Teary Mark",					"gen": 8,	"title": "the Teary-Eyed",			"available": null, "mark": true, "desc": "A mark for a teary-eyed Pokémon."},
	"upbeat-mark":					{"name": "Upbeat Mark",					"gen": 8,	"title": "the Chipper",				"available": null, "mark": true, "desc": "A mark for a chipper Pokémon."},
	"peeved-mark":					{"name": "Peeved Mark",					"gen": 8,	"title": "the Grumpy",				"available": null, "mark": true, "desc": "A mark for a grumpy Pokémon."},
	"intellectual-mark":			{"name": "Intellectual Mark",			"gen": 8,	"title": "the Scholar",				"available": null, "mark": true, "desc": "A mark for a scholarly Pokémon."},
	"ferocious-mark":				{"name": "Ferocious Mark",				"gen": 8,	"title": "the Rampaging",			"available": null, "mark": true, "desc": "A mark for a rampaging Pokémon."},
	"crafty-mark":					{"name": "Crafty Mark",					"gen": 8,	"title": "the Opportunist",			"available": null, "mark": true, "desc": "A mark for an opportunistic Pokémon."},
	"scowling-mark":				{"name": "Scowling Mark",				"gen": 8,	"title": "the Stern",				"available": null, "mark": true, "desc": "A mark for a stern Pokémon."},
	"kindly-mark":					{"name": "Kindly Mark",					"gen": 8,	"title": "the Kindhearted",			"available": null, "mark": true, "desc": "A mark for a kindhearted Pokémon."},
	"flustered-mark":				{"name": "Flustered Mark",				"gen": 8,	"title": "the Easily Flustered",	"available": null, "mark": true, "desc": "A mark for an easily flustered Pokémon."},
	"pumped-up-mark":				{"name": "Pumped-Up Mark",				"gen": 8,	"title": "the Driven",				"available": null, "mark": true, "desc": "A mark for a driven Pokémon."},
	"zero-energy-mark":				{"name": "Zero Energy Mark",			"gen": 8,	"title": "the Apathetic",			"available": null, "mark": true, "desc": "A mark for an apathetic Pokémon."},
	"prideful-mark":				{"name": "Prideful Mark",				"gen": 8,	"title": "the Arrogant",			"available": null, "mark": true, "desc": "A mark for an arrogant Pokémon."},
	"unsure-mark":					{"name": "Unsure Mark",					"gen": 8,	"title": "the Reluctant",			"available": null, "mark": true, "desc": "A mark for an unsure Pokémon."},
	"humble-mark":					{"name": "Humble Mark",					"gen": 8,	"title": "the Humble",				"available": null, "mark": true, "desc": "A mark for a humble Pokémon."},
	"thorny-mark":					{"name": "Thorny Mark",					"gen": 8,	"title": "the Pompous",				"available": null, "mark": true, "desc": "A mark for a pompous Pokémon."},
	"vigor-mark":					{"name": "Vigor Mark",					"gen": 8,	"title": "the Lively",				"available": null, "mark": true, "desc": "A mark for a lively Pokémon."},
	"slump-mark":					{"name": "Slump Mark",					"gen": 8,	"title": "the Worn-Out",			"available": null, "mark": true, "desc": "A mark for a worn-out Pokémon."}
}
